### ISSUE TITLE
Trying to install in wordpress.

### ISSUE THREAD

**Issue by DaemonDB** [osseed/com.osseed.eventcalendar#93]
I receive the civix error:

[09-May-2022 23:03:28 UTC] PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in
/bitnami/wordpress/wp-content/uploads/civicrm/ext/com.osseed.eventcalendar/eventcalendar.civix.php on line 246

Any work arounds?

D

**Comment by osseed** [comment]
@DaemonDB Can you please add details of WP and CiviCRM version and php version also.

**Comment by choess** [comment]
I experienced a similar problem when I upgraded the underlying system to Ubuntu 22.04.1, during which php7.4 was removed in favor of php8.1. (The system is up-to-date: Drupal 9.4.5, CiviCRM 5.53.0) After that, the extension started bringing down my Drupal installation with the following error:
`PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /var/www/serpsproject/web/sites/default/files/civicrm/ext/com.osseed.eventcalendar/eventcalendar.civix.php on line 246`

It looks like this syntax was fixed in [this commit](https://github.com/osseed/com.osseed.eventcalendar/commit/3fb3809b229705b109d6241c00575d5646072727) shortly after the 4.1 release. I would expect that cutting a new release based on the current codebase would fix the problem. Manually changing curly to square braces on that line would probably fix the problem pending that, but it would be nice to take advantage of the other updates.
